### ISSUE TITLE
How can I get the result in the first GIF?

### ISSUE THREAD

**Issue by lmy931** [koomg9599/Body_Pose_Estimation_Android#7]
This is really an interesting repo. I ran this project and get the results like shown in the second and third GIF. The question is how can I get the result in the first GIF?

**Comment by kooku0** [comment]
Thank you for your interest. I refer to the Tensorflow Lite example code. 
https://github.com/tensorflow/examples/tree/master/lite/examples/gesture_classification/android
I hope this will help.
