### ISSUE TITLE
How to integrate your code with the 'Tensorflow Lite example code' ?

### ISSUE THREAD

**Issue by lmy931** [koomg9599/Body_Pose_Estimation_Android#8]
I think the 'Tensorflow Lite example code' is used to do gesture classification, not BodyPoseEstimation. 
I saw your first GIF and I believe you can do bodyPoseEstimation and switch between CPU and GPU. Can you provide this code? Thanks 3000 times!

**Comment by kooku0** [comment]
Sorry, I used only template.
switch function doesn't work.
Why don't you look this code?
https://github.com/dongseokYang/Body-Pose-Estimation-Android-gpu
my code was based on this code.

**Comment by lmy931** [comment]
I saw it before, it doesn't work properly.

**Comment by lmy931** [comment]
It seems that it does not deal with the output, say nothing about showing keypoints/lines.

![image](https://user-images.githubusercontent.com/38743605/58236458-1864f200-7d82-11e9-8e23-da710b3f990d.png)
